[versions]
# Plugins
kotlin = "2.3.10"
kotlinter = "5.4.2"
buildconfig = "6.0.7"
versions = "0.53.0"

# Libraries
coroutines = "1.10.2"
dropwizard = "4.2.38"
kotest = "6.1.3"
ktor = "3.4.0"
logback = "1.5.29"
logging = "7.0.14"
text = "1.15.0"
utils = "2.5.3"

[libraries]
# Kotlin
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

# Ktor
ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio" }
ktor-server-html = { module = "io.ktor:ktor-server-html-builder" }
ktor-client-core = { module = "io.ktor:ktor-client-core" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio" }

# Utils
utils-bom = { module = "com.github.pambrose.common-utils:common-utils-bom", version.ref = "utils" }
utils-core = { module = "com.github.pambrose.common-utils:core-utils" }
utils-ktor-server = { module = "com.github.pambrose.common-utils:ktor-server-utils" }

# Metrics
dropwizard-bom = { module = "io.dropwizard.metrics:metrics-bom", version.ref = "dropwizard" }
dropwizard-core = { module = "io.dropwizard.metrics:metrics-core" }
dropwizard-jvm = { module = "io.dropwizard.metrics:metrics-jvm" }

# Other
commons-text = { module = "org.apache.commons:commons-text", version.ref = "text" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "logging" }

# Testing
kotest = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
ktor-plugin = { id = "io.ktor.plugin", version.ref = "ktor" }

[bundles]
ktor = [
  "ktor-server-core",
  "ktor-server-cio",
  "ktor-server-html",
  "ktor-client-core",
  "ktor-client-cio",
]

common-utils = [
  "utils-core",
  "utils-ktor-server",
]

dropwizard = [
  "dropwizard-core",
  "dropwizard-jvm",
]
